### ISSUE TITLE
items in pum are highlighted in wrong direction.

### ISSUE THREAD

**Issue by jmatraszek** [ervandew/supertab#16]
Hi.
When pop up menu is visible with options to choose pressing tab causes changing highlighted item from bottom to top. Pressing tab highlights third item, then second, then first one. It works like <C-n> completion, not <C-p>
I've got SuperTabDefaultCompletionType set to <c-p>, SuperTabMappingForward set to <tab> and SuperTabMappingBackward set to <s-tab>.
<C-p> completion works good.
Is there any other setting I should consider for making this to work right?
I'll try to investigate and provide some more details.

**Comment by unphased** [comment]
Hi @ervandew. I appreciate your explanation (just like you also explained in the Readme). I believe I understand this fully, but I am not 100% sure. 

So perhaps my question might really technically be for Bram, but I am hopeful that you know whether it is possible to configure things to my liking. I'm also hopeful that my preference might be shared by others. 

1. The behavior of first highlighting the matching item in the buffer before/above the cursor is absolutely a great default. I had been using supertab for a bit and this basic heuristic appears to account for a lot of its magic! It is such a simple trick to start from the bottom by default, it picks a better starting point almost always.

I'm used to using other completion plugins, and supertab is the most "low level" one that I have used yet. There is no way I would put up with typing anything more than one tab keystroke (such as two consecutive chords, which I understand is needed for not using a completion plugin?) to prompt completion. Usually I'd prefer the behavior from some completers such as auto-displaying it as you type, but I am definitely taking a liking to the "speak when you're told" demeanor now. Sorry for this digression.

2. Many of us are understandably pretty used to the completion menu focus starting at the top and moving downward. I have no intrinsic problem with the upward motion, it is different from what i'm used to, but the main usability "problem" if you will is that the point of focus on the screen jumps an inconsistent amount of lines lower on the screen when the completion menu is invoked. The solution to this would be to make all of the behavior exactly the same but reverse the display of the menu. I understand that this is entirely outside of the purview of Supertab, but do you know if configuration exists in vim (or neovim, which, ironically i use with supertab only with nvim, i use coc.nvim when running vim and it handles completion for me) to *reverse* the results, putting the nearest match above the cursor on the TOP of the menu instead of the bottom?

3. This is actually off-topic, but I couldn't help myself from adding this question in, even though I know the answer... I really like the minimalism of this plugin but I just wish I could type the initial letters of a symbol and have it prioritize picking it. e.g. `my_var_name` can get sorted first when I type `mvn<tab>`. Yes the answer is use a fancier completer plugin. 

Thanks!
