### ISSUE TITLE
secondary complete line completion?

### ISSUE THREAD

**Issue by fncll** [ervandew/supertab#85]
I'm trying to figure out how to configure SuperTab to first offer individual word completion and then full-line completions. Is there a way to do so?

In other words, if I have a line

`set foobar=x`

then I'd like, at:

`set fo`

to first complete `foobar` and then, if I tab again, complete `foobar=x`

**Comment by sts10** [comment]
I think `<C-x><C-l>` in insert mode does line-wise completion in default Vim. I have it mapped to shift tab: `inoremap <S-Tab> <C-x><C-l>`. This remapping doesn't seem to affect SuperTab's behavior (which is good!). 

But maybe you could work this into SuperTab as a line-wise option?

**Comment by ervandew** [comment]
@sts10 
This issue pre-dates supertab's completion chaining support, but even with that supertab can't support chaining these two types of completions together since there is no mechanism in vim to detect if the first completion returned any results or not. Chaining is limited to completions that provide a function that supertab can call (user and omni completion), followed by any other completion that can be issued by sending a key combination (keyword, line, etc.).  If you want line completion as the default or as the fallback after user/omni completion, then that should work just fine with supertab.
